# Generated by Django 5.1.4 on 2024-12-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_user_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName1', models.CharField(max_length=100)),
                ('emailId1', models.EmailField(max_length=254, unique=True)),
                ('phoneNo1', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tb_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('emailID', models.EmailField(max_length=254, unique=True)),
                ('phoneNo', models.CharField(max_length=15)),
            ],
        ),
    ]
