# Generated by Django 5.1.4 on 2024-12-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_tb_course_tb_faculty_tb_lesson_plan_tb_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('student_programme', models.CharField(max_length=45)),
                ('student_branch', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tb_student',
            },
        ),
        migrations.RenameField(
            model_name='tb_lesson_plan',
            old_name='co_no',
            new_name='co_num',
        ),
        migrations.AddField(
            model_name='tb_faculty',
            name='designation',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_faculty',
            name='seniority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_lesson_plan',
            name='academic_year',
            field=models.IntegerField(default=2425),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tb_faculty',
            name='faculty_id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
