# Generated by Django 5.1.4 on 2024-12-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_tb_student_rename_co_no_tb_lesson_plan_co_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_AssessmentPlan',
            fields=[
                ('component', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mid_sem_exam', models.TextField(blank=True, null=True)),
                ('flexible_assessments', models.TextField(blank=True, null=True)),
                ('end_semester_exam', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_AssessmentPlan',
            },
        ),
    ]
