# Generated by Django 5.1.4 on 2024-12-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_tb_assessmentplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tb_course',
            new_name='tb_course1',
        ),
        migrations.AlterModelTable(
            name='tb_course1',
            table='tb_course1',
        ),
    ]
