# Generated by Django 5.1.4 on 2024-12-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_tb_course_tb_course1_alter_tb_course1_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tb_course1',
            new_name='tb_course',
        ),
        migrations.AlterModelTable(
            name='tb_course',
            table='tb_course',
        ),
    ]
