# Generated by Django 5.1.4 on 2024-12-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_tb_course_faculty_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_course',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
