# Generated by Django 5.1.4 on 2024-12-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_tb_course_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_lesson_plan',
            name='course_id',
        ),
        migrations.AddField(
            model_name='tb_lesson_plan',
            name='course_code',
            field=models.CharField(default='Default Code', max_length=45),
            preserve_default=False,
        ),
    ]
