# Generated by Django 5.1.4 on 2024-12-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_tb_lesson_plan_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_lesson_plan',
            name='lesson_id',
            field=models.CharField(max_length=10),
        ),
    ]
